services:

  # PRODUCTION 
  sql_ai_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sql_ai_app
    ports:
      - "8001:8000"

  # LOCAL
#   mysql_shared:
#     image: mysql:8.0
#     container_name: laravel_ai_mysql
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: default_db
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#     volumes:
#       - mysql_shared_data:/var/lib/mysql

#   sql_ai_app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: sql_ai_app
#     working_dir: /var/www/html
#     volumes:
#       - ./sql-ai:/var/www/html
#     ports:
#       - "8001:8000"
#     depends_on:
#       - mysql_shared

# volumes:
#   mysql_shared_data: