name: Deploy Laravel Docker

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd laravel-ai-workspace-sql-app

            git pull origin main

            docker-compose down
            docker-compose up -d --build

            echo "⏳ Waiting for MySQL..."

            for i in {1..30}; do
              docker exec laravel_ai_mysql mysqladmin ping -h"localhost" --silent && break
              echo "Waiting for MySQL... ($i)"
              sleep 2
            done

            echo "🔄 Restarting Laravel container..."
            docker restart sql_ai_app

            echo "🧹 Clearing config cache..."
            docker exec sql_ai_app php artisan config:clear

            echo "🚀 Running migrations..."
            docker exec sql_ai_app php artisan migrate --force
